# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.0
    - extra-android-m2repository
    - extra-android-support

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - sh buildsystem/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
